package modelo.dto;
// Generated 15-09-2021 23:35:47 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Equipo generated by hbm2java
 */

// Falta validar

public class Equipo implements java.io.Serializable {

    private Integer id;
    private Liga liga;
    private PerfilJugador perfilJugador;
    private String nombre;
    private int cantidadJugador;
    private Set detalleEquipos = new HashSet(0);
    
    public Equipo() {
    }
    
    public Equipo(Integer id) {
        setId(id);
    }
    
    public Equipo(Integer id, Liga liga, String nombre) {
        setId(id);
        setLiga(liga);
        setNombre(nombre);
    }
    
    public Equipo(Liga liga, String nombre) {
        setLiga(liga);
        setNombre(nombre);
    }
    
    public Equipo(Integer id, Liga liga, PerfilJugador perfilJugador, String nombre, int cantidadJugador) {
        setId(id);
        setLiga(liga);
        setPerfilJugador(perfilJugador);
        setNombre(nombre);
        setCantidadJugador(cantidadJugador);
    }

    public Equipo(Integer id, Liga liga, PerfilJugador perfilJugador, String nombre, int cantidadJugador, Set detalleEquipos) {
        setId(id);
        setLiga(liga);
        setPerfilJugador(perfilJugador);
        setNombre(nombre);
        setCantidadJugador(cantidadJugador);
        setDetalleEquipos(detalleEquipos);
    }
    
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public Liga getLiga() {
        return this.liga;
    }
    
    public void setLiga(Liga liga) {
        this.liga = liga;
    }

    public PerfilJugador getPerfilJugador() {
        return this.perfilJugador;
    }
    
    public void setPerfilJugador(PerfilJugador perfilJugador) {
        this.perfilJugador = perfilJugador;
    }

    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public int getCantidadJugador() {
        return this.cantidadJugador;
    }
    
    public void setCantidadJugador(int cantidadJugador) {
        this.cantidadJugador = cantidadJugador;
    }

    public Set getDetalleEquipos() {
        return this.detalleEquipos;
    }
    
    public void setDetalleEquipos(Set detalleEquipos) {
        this.detalleEquipos = detalleEquipos;
    }
    
}
