package modelo.dto;
// Generated 13-09-2021 22:41:06 by Hibernate Tools 4.3.1



/**
 * Equipo generated by hbm2java
 */
public class Equipo  implements java.io.Serializable {


     private Integer id;
     private Incripcion incripcion;
     private Liga liga;
     private String nombre;
     private int cantidadJugador;

    public Equipo() {
    }

    public Equipo(Incripcion incripcion, Liga liga, String nombre, int cantidadJugador) {
       this.incripcion = incripcion;
       this.liga = liga;
       this.nombre = nombre;
       this.cantidadJugador = cantidadJugador;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Incripcion getIncripcion() {
        return this.incripcion;
    }
    
    public void setIncripcion(Incripcion incripcion) {
        this.incripcion = incripcion;
    }
    public Liga getLiga() {
        return this.liga;
    }
    
    public void setLiga(Liga liga) {
        this.liga = liga;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getCantidadJugador() {
        return this.cantidadJugador;
    }
    
    public void setCantidadJugador(int cantidadJugador) {
        this.cantidadJugador = cantidadJugador;
    }




}


