package modelo.dto;
// Generated 13-09-2021 17:55:00 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * EstadoSolicitud generated by hbm2java
 */
public class EstadoSolicitud  implements java.io.Serializable {


     private Integer idEstado;
     private String descripcion;
     private Set incripcions = new HashSet(0);

    public EstadoSolicitud() {
    }

	
    public EstadoSolicitud(String descripcion) {
        this.descripcion = descripcion;
    }
    public EstadoSolicitud(String descripcion, Set incripcions) {
       this.descripcion = descripcion;
       this.incripcions = incripcions;
    }
   
    public Integer getIdEstado() {
        return this.idEstado;
    }
    
    public void setIdEstado(Integer idEstado) {
        this.idEstado = idEstado;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getIncripcions() {
        return this.incripcions;
    }
    
    public void setIncripcions(Set incripcions) {
        this.incripcions = incripcions;
    }




}


