package modelo.dto;
// Generated 13-09-2021 19:04:06 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Incripcion generated by hbm2java
 */
public class Incripcion  implements java.io.Serializable {


     private Integer id;
     private EstadoSolicitud estadoSolicitud;
     private PerfilJugador perfilJugador;
     private Date fecha;
     private Set equipos = new HashSet(0);

    public Incripcion() {
    }

	
    public Incripcion(EstadoSolicitud estadoSolicitud, PerfilJugador perfilJugador, Date fecha) {
        this.estadoSolicitud = estadoSolicitud;
        this.perfilJugador = perfilJugador;
        this.fecha = fecha;
    }
    public Incripcion(EstadoSolicitud estadoSolicitud, PerfilJugador perfilJugador, Date fecha, Set equipos) {
       this.estadoSolicitud = estadoSolicitud;
       this.perfilJugador = perfilJugador;
       this.fecha = fecha;
       this.equipos = equipos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public EstadoSolicitud getEstadoSolicitud() {
        return this.estadoSolicitud;
    }
    
    public void setEstadoSolicitud(EstadoSolicitud estadoSolicitud) {
        this.estadoSolicitud = estadoSolicitud;
    }
    public PerfilJugador getPerfilJugador() {
        return this.perfilJugador;
    }
    
    public void setPerfilJugador(PerfilJugador perfilJugador) {
        this.perfilJugador = perfilJugador;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Set getEquipos() {
        return this.equipos;
    }
    
    public void setEquipos(Set equipos) {
        this.equipos = equipos;
    }




}


