package modelo.dto;
// Generated 15-09-2021 23:35:47 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Liga generated by hbm2java
 */
// Falta validar
public class Liga implements java.io.Serializable {
    
    private Integer id;
    private VideoJuego videoJuego;
    private String descripcion;
    private int cantidadEquipo;
    private Set equipos = new HashSet(0);
    
    public Liga() {
    }
    
    public Liga(Integer id) {
        setId(id);
    }
    
    public Liga(VideoJuego videoJuego, String descripcion, int cantidadEquipo) {
        setVideoJuego(videoJuego);
        setDescripcion(descripcion);
        setCantidadEquipo(cantidadEquipo);
    }
    
    public Liga(Integer id, VideoJuego videoJuego, String descripcion) {
        setId(id);
        setVideoJuego(videoJuego);
        setDescripcion(descripcion);
    }
    
    public Liga(VideoJuego videoJuego, String descripcion) {
        this.videoJuego = videoJuego;
        this.descripcion = descripcion;
    }    
    
    public Liga(Integer id, VideoJuego videoJuego, String descripcion, int cantidadEquipo) {
        setId(id);
        setVideoJuego(videoJuego);
        setDescripcion(descripcion);
        setCantidadEquipo(cantidadEquipo);
    }

    public Liga(Integer id, VideoJuego videoJuego, String descripcion, int cantidadEquipo, Set equipos) {
        setId(id);
        setVideoJuego(videoJuego);
        setDescripcion(descripcion);
        setCantidadEquipo(cantidadEquipo);
        setEquipos(equipos);
    }
    
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public VideoJuego getVideoJuego() {
        return this.videoJuego;
    }
    
    public void setVideoJuego(VideoJuego videoJuego) {
        this.videoJuego = videoJuego;
    }

    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public int getCantidadEquipo() {
        return this.cantidadEquipo;
    }
    
    public void setCantidadEquipo(int cantidadEquipo) {
        this.cantidadEquipo = cantidadEquipo;
    }

    public Set getEquipos() {
        return this.equipos;
    }
    
    public void setEquipos(Set equipos) {
        this.equipos = equipos;
    }
    
}
