package modelo.dto;
// Generated 13-09-2021 17:55:00 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * PerfilJugador generated by hbm2java
 */
public class PerfilJugador  implements java.io.Serializable {


     private Integer idJugador;
     private TipoJugador tipoJugador;
     private Usuario usuario;
     private String nombre;
     private String correo;
     private Set incripcions = new HashSet(0);

    public PerfilJugador() {
    }

	
    public PerfilJugador(TipoJugador tipoJugador, Usuario usuario, String nombre, String correo) {
        this.tipoJugador = tipoJugador;
        this.usuario = usuario;
        this.nombre = nombre;
        this.correo = correo;
    }
    public PerfilJugador(TipoJugador tipoJugador, Usuario usuario, String nombre, String correo, Set incripcions) {
       this.tipoJugador = tipoJugador;
       this.usuario = usuario;
       this.nombre = nombre;
       this.correo = correo;
       this.incripcions = incripcions;
    }
   
    public Integer getIdJugador() {
        return this.idJugador;
    }
    
    public void setIdJugador(Integer idJugador) {
        this.idJugador = idJugador;
    }
    public TipoJugador getTipoJugador() {
        return this.tipoJugador;
    }
    
    public void setTipoJugador(TipoJugador tipoJugador) {
        this.tipoJugador = tipoJugador;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public Set getIncripcions() {
        return this.incripcions;
    }
    
    public void setIncripcions(Set incripcions) {
        this.incripcions = incripcions;
    }




}


