package modelo.dto;
// Generated 13-09-2021 17:55:00 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoJugador generated by hbm2java
 */
public class TipoJugador  implements java.io.Serializable {


     private Integer idTipoJugador;
     private String descripcion;
     private Set perfilJugadors = new HashSet(0);

    public TipoJugador() {
    }

	
    public TipoJugador(String descripcion) {
        this.descripcion = descripcion;
    }
    public TipoJugador(String descripcion, Set perfilJugadors) {
       this.descripcion = descripcion;
       this.perfilJugadors = perfilJugadors;
    }
   
    public Integer getIdTipoJugador() {
        return this.idTipoJugador;
    }
    
    public void setIdTipoJugador(Integer idTipoJugador) {
        this.idTipoJugador = idTipoJugador;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getPerfilJugadors() {
        return this.perfilJugadors;
    }
    
    public void setPerfilJugadors(Set perfilJugadors) {
        this.perfilJugadors = perfilJugadors;
    }




}


