package modelo.dto;
// Generated 13-09-2021 17:55:00 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * VideoJuego generated by hbm2java
 */
public class VideoJuego  implements java.io.Serializable {


     private Integer idJuego;
     private String nombre;
     private String tipoJuego;
     private Set ligas = new HashSet(0);

    public VideoJuego() {
    }

	
    public VideoJuego(String nombre, String tipoJuego) {
        this.nombre = nombre;
        this.tipoJuego = tipoJuego;
    }
    public VideoJuego(String nombre, String tipoJuego, Set ligas) {
       this.nombre = nombre;
       this.tipoJuego = tipoJuego;
       this.ligas = ligas;
    }
   
    public Integer getIdJuego() {
        return this.idJuego;
    }
    
    public void setIdJuego(Integer idJuego) {
        this.idJuego = idJuego;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getTipoJuego() {
        return this.tipoJuego;
    }
    
    public void setTipoJuego(String tipoJuego) {
        this.tipoJuego = tipoJuego;
    }
    public Set getLigas() {
        return this.ligas;
    }
    
    public void setLigas(Set ligas) {
        this.ligas = ligas;
    }




}


